name: Deployment

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2

    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Install cargo-make
      uses: davidB/rust-cargo-make@v1

    - name: Install wasm-pack
      uses: jetli/wasm-pack-action@v0.3.0

    - name: Cache crates and build artifacts
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Build
      run: cargo make build_release

    - name: Prepare publishing
      run: |
        mkdir html
        rm pkg/.gitignore
        mv css pkg index.html html

    - name: Publish
      if: success()
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: gh-pages
        build_dir: html
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
